development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: 1234abc 
  database: ExteUTF_development

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: 1234abc
  database: ExteUTF_test

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: 1234abc
  database: ExteUTF_production